// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskResultTransfer_Upload_FullMethodName = "/filetransfer.TaskResultTransfer/Upload"
)

// TaskResultTransferClient is the client API for TaskResultTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 上传任务执行结果
type TaskResultTransferClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TaskResult, TaskResponse], error)
}

type taskResultTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskResultTransferClient(cc grpc.ClientConnInterface) TaskResultTransferClient {
	return &taskResultTransferClient{cc}
}

func (c *taskResultTransferClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TaskResult, TaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskResultTransfer_ServiceDesc.Streams[0], TaskResultTransfer_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskResult, TaskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskResultTransfer_UploadClient = grpc.ClientStreamingClient[TaskResult, TaskResponse]

// TaskResultTransferServer is the server API for TaskResultTransfer service.
// All implementations must embed UnimplementedTaskResultTransferServer
// for forward compatibility.
//
// 上传任务执行结果
type TaskResultTransferServer interface {
	Upload(grpc.ClientStreamingServer[TaskResult, TaskResponse]) error
	mustEmbedUnimplementedTaskResultTransferServer()
}

// UnimplementedTaskResultTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskResultTransferServer struct{}

func (UnimplementedTaskResultTransferServer) Upload(grpc.ClientStreamingServer[TaskResult, TaskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedTaskResultTransferServer) mustEmbedUnimplementedTaskResultTransferServer() {}
func (UnimplementedTaskResultTransferServer) testEmbeddedByValue()                            {}

// UnsafeTaskResultTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskResultTransferServer will
// result in compilation errors.
type UnsafeTaskResultTransferServer interface {
	mustEmbedUnimplementedTaskResultTransferServer()
}

func RegisterTaskResultTransferServer(s grpc.ServiceRegistrar, srv TaskResultTransferServer) {
	// If the following call pancis, it indicates UnimplementedTaskResultTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskResultTransfer_ServiceDesc, srv)
}

func _TaskResultTransfer_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskResultTransferServer).Upload(&grpc.GenericServerStream[TaskResult, TaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskResultTransfer_UploadServer = grpc.ClientStreamingServer[TaskResult, TaskResponse]

// TaskResultTransfer_ServiceDesc is the grpc.ServiceDesc for TaskResultTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskResultTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filetransfer.TaskResultTransfer",
	HandlerType: (*TaskResultTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _TaskResultTransfer_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}

const (
	RecordTransfer_Transfer_FullMethodName = "/filetransfer.RecordTransfer/Transfer"
)

// RecordTransferClient is the client API for RecordTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 接收agent心跳
type RecordTransferClient interface {
	Transfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Record, Task], error)
}

type recordTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordTransferClient(cc grpc.ClientConnInterface) RecordTransferClient {
	return &recordTransferClient{cc}
}

func (c *recordTransferClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Record, Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecordTransfer_ServiceDesc.Streams[0], RecordTransfer_Transfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Record, Task]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordTransfer_TransferClient = grpc.BidiStreamingClient[Record, Task]

// RecordTransferServer is the server API for RecordTransfer service.
// All implementations must embed UnimplementedRecordTransferServer
// for forward compatibility.
//
// 接收agent心跳
type RecordTransferServer interface {
	Transfer(grpc.BidiStreamingServer[Record, Task]) error
	mustEmbedUnimplementedRecordTransferServer()
}

// UnimplementedRecordTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordTransferServer struct{}

func (UnimplementedRecordTransferServer) Transfer(grpc.BidiStreamingServer[Record, Task]) error {
	return status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedRecordTransferServer) mustEmbedUnimplementedRecordTransferServer() {}
func (UnimplementedRecordTransferServer) testEmbeddedByValue()                        {}

// UnsafeRecordTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordTransferServer will
// result in compilation errors.
type UnsafeRecordTransferServer interface {
	mustEmbedUnimplementedRecordTransferServer()
}

func RegisterRecordTransferServer(s grpc.ServiceRegistrar, srv RecordTransferServer) {
	// If the following call pancis, it indicates UnimplementedRecordTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordTransfer_ServiceDesc, srv)
}

func _RecordTransfer_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RecordTransferServer).Transfer(&grpc.GenericServerStream[Record, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordTransfer_TransferServer = grpc.BidiStreamingServer[Record, Task]

// RecordTransfer_ServiceDesc is the grpc.ServiceDesc for RecordTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filetransfer.RecordTransfer",
	HandlerType: (*RecordTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _RecordTransfer_Transfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
