// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: grpc.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskTransfer_Upload_FullMethodName = "/filetransfer.TaskTransfer/Upload"
)

// TaskTransferClient is the client API for TaskTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 上传任务执行结果，返回结果响应
type TaskTransferClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Task, TaskResponse], error)
}

type taskTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskTransferClient(cc grpc.ClientConnInterface) TaskTransferClient {
	return &taskTransferClient{cc}
}

func (c *taskTransferClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Task, TaskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskTransfer_ServiceDesc.Streams[0], TaskTransfer_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Task, TaskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskTransfer_UploadClient = grpc.ClientStreamingClient[Task, TaskResponse]

// TaskTransferServer is the server API for TaskTransfer service.
// All implementations must embed UnimplementedTaskTransferServer
// for forward compatibility.
//
// 上传任务执行结果，返回结果响应
type TaskTransferServer interface {
	Upload(grpc.ClientStreamingServer[Task, TaskResponse]) error
	mustEmbedUnimplementedTaskTransferServer()
}

// UnimplementedTaskTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskTransferServer struct{}

func (UnimplementedTaskTransferServer) Upload(grpc.ClientStreamingServer[Task, TaskResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedTaskTransferServer) mustEmbedUnimplementedTaskTransferServer() {}
func (UnimplementedTaskTransferServer) testEmbeddedByValue()                      {}

// UnsafeTaskTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskTransferServer will
// result in compilation errors.
type UnsafeTaskTransferServer interface {
	mustEmbedUnimplementedTaskTransferServer()
}

func RegisterTaskTransferServer(s grpc.ServiceRegistrar, srv TaskTransferServer) {
	// If the following call pancis, it indicates UnimplementedTaskTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskTransfer_ServiceDesc, srv)
}

func _TaskTransfer_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskTransferServer).Upload(&grpc.GenericServerStream[Task, TaskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TaskTransfer_UploadServer = grpc.ClientStreamingServer[Task, TaskResponse]

// TaskTransfer_ServiceDesc is the grpc.ServiceDesc for TaskTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filetransfer.TaskTransfer",
	HandlerType: (*TaskTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _TaskTransfer_Upload_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}

const (
	RecordTransfer_Transfer_FullMethodName = "/filetransfer.RecordTransfer/Transfer"
)

// RecordTransferClient is the client API for RecordTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 接收agent心跳，下发task
type RecordTransferClient interface {
	Transfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Record, Task], error)
}

type recordTransferClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordTransferClient(cc grpc.ClientConnInterface) RecordTransferClient {
	return &recordTransferClient{cc}
}

func (c *recordTransferClient) Transfer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Record, Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RecordTransfer_ServiceDesc.Streams[0], RecordTransfer_Transfer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Record, Task]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordTransfer_TransferClient = grpc.BidiStreamingClient[Record, Task]

// RecordTransferServer is the server API for RecordTransfer service.
// All implementations must embed UnimplementedRecordTransferServer
// for forward compatibility.
//
// 接收agent心跳，下发task
type RecordTransferServer interface {
	Transfer(grpc.BidiStreamingServer[Record, Task]) error
	mustEmbedUnimplementedRecordTransferServer()
}

// UnimplementedRecordTransferServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordTransferServer struct{}

func (UnimplementedRecordTransferServer) Transfer(grpc.BidiStreamingServer[Record, Task]) error {
	return status.Errorf(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedRecordTransferServer) mustEmbedUnimplementedRecordTransferServer() {}
func (UnimplementedRecordTransferServer) testEmbeddedByValue()                        {}

// UnsafeRecordTransferServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordTransferServer will
// result in compilation errors.
type UnsafeRecordTransferServer interface {
	mustEmbedUnimplementedRecordTransferServer()
}

func RegisterRecordTransferServer(s grpc.ServiceRegistrar, srv RecordTransferServer) {
	// If the following call pancis, it indicates UnimplementedRecordTransferServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordTransfer_ServiceDesc, srv)
}

func _RecordTransfer_Transfer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RecordTransferServer).Transfer(&grpc.GenericServerStream[Record, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RecordTransfer_TransferServer = grpc.BidiStreamingServer[Record, Task]

// RecordTransfer_ServiceDesc is the grpc.ServiceDesc for RecordTransfer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordTransfer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "filetransfer.RecordTransfer",
	HandlerType: (*RecordTransferServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transfer",
			Handler:       _RecordTransfer_Transfer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc.proto",
}
